version: '3'
services:
  client:
    build: client
    ports:
      - '8080:8080'
  server:
    build: server
    environment:
      - PORT=3000
      - BASE_API_URL=api
      - CLIENT_URL=https://mern-ecommerce-seven-murex.vercel.app
      - JWT_SECRET=update_your_JWT_secret
      - MONGO_URI=mongodb+srv://devroyale:devroyale@mernapp.dxzuwbs.mongodb.net/?retryWrites=true&w=majority
    ports:
      - '3000:3000'
